language: java
jdk:
- openjdk8
after_success:
- mvn clean test jacoco:report coveralls:report
before_install:
- openssl aes-256-cbc -K $encrypted_29289bc7c3ec_key -iv $encrypted_29289bc7c3ec_iv
  -in .travis.appengine.json.enc -out .travis.appengine.json -d
deploy:
  provider: gae
  keyfile: .travis.appengine.json
  project: rssreader-184322
